title: Leon Sun - Data Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Leon Sun. Welcome to my personal data analytics portfolio! 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leonswl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Leon Sun # add your name
author-img: '/leon-small.jpg' # add your photo
about-author: I work with data and enjoys spending my free time finding interesting projects to work on. I'm currently a data analyst at BetterTradeOff, focusing on building our data platform and generating insights to empower app development. Proficient in python, SQL and R! # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: leonswl # add your Github handle
social-linkedin: leonsunwailoong # add your Linkedin handle
social-email: leonsunwl@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
